/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ProgressBar {
    'progress': number;
  }
  interface SliderApp {
    'max': number;
    'min': number;
    'value': number;
  }
}

declare global {


  interface HTMLProgressBarElement extends Components.ProgressBar, HTMLStencilElement {}
  var HTMLProgressBarElement: {
    prototype: HTMLProgressBarElement;
    new (): HTMLProgressBarElement;
  };

  interface HTMLSliderAppElement extends Components.SliderApp, HTMLStencilElement {}
  var HTMLSliderAppElement: {
    prototype: HTMLSliderAppElement;
    new (): HTMLSliderAppElement;
  };
  interface HTMLElementTagNameMap {
    'progress-bar': HTMLProgressBarElement;
    'slider-app': HTMLSliderAppElement;
  }
}

declare namespace LocalJSX {
  interface ProgressBar {
    'onProgressDone'?: (event: CustomEvent<any>) => void;
    'progress'?: number;
  }
  interface SliderApp {
    'max'?: number;
    'min'?: number;
    'onValueChanged'?: (event: CustomEvent<any>) => void;
    'value'?: number;
  }

  interface IntrinsicElements {
    'progress-bar': ProgressBar;
    'slider-app': SliderApp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'progress-bar': LocalJSX.ProgressBar & JSXBase.HTMLAttributes<HTMLProgressBarElement>;
      'slider-app': LocalJSX.SliderApp & JSXBase.HTMLAttributes<HTMLSliderAppElement>;
    }
  }
}


